name: lint_maker
description: >-
  A script to help you create custom linting configurations.
  Creates analysis_options.yaml files to your liking.
version: 0.2.1
repository: https://github.com/debacode/lint_maker
issue_tracker: https://github.com/debacode/lint_maker/issues
topics:
  - analysis
  - lints

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.2.0 <7.0.0"
  checked_yaml: ^2.0.3
  http: ^1.0.0
  json2yaml: ^3.0.1
  json_annotation: ^4.6.0
  version: ^3.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.3.2
  pana: ^0.22.0
  test: ^1.24.6

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

executables:
  lint_maker:
