name: lint_maker
description: Custom linting maker. Creates analysis_options.yaml files to your liking.
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  checked_yaml: ^2.0.3
  copy_with_extension: ^5.0.4
  http: ^1.1.0
  json2yaml: ^3.0.1
  json_annotation: ^4.8.1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  json_serializable: ^6.7.1
  test: ^1.24.6
